// <auto-generated />
using System;
using DBHandler.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DBHandler.Migrations
{
    [DbContext(typeof(DBHandlerContext))]
    [Migration("20250905010054_InitialCreate1234")]
    partial class InitialCreate1234
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DBHandler.Models.Campo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("BOOLEAN");

                    b.Property<int?>("EtapaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("FlujoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Opciones")
                        .HasColumnType("CLOB");

                    b.Property<int>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<bool>("Requerido")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("EtapaId");

                    b.HasIndex("FlujoId");

                    b.ToTable("CAMPOS", (string)null);
                });

            modelBuilder.Entity("DBHandler.Models.Etapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Detalle")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("FlujoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("FlujoId");

                    b.ToTable("ETAPAS", (string)null);
                });

            modelBuilder.Entity("DBHandler.Models.EtapaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Detalle")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("EtapaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("EtapaId");

                    b.ToTable("ETAPA_DETALLES", (string)null);
                });

            modelBuilder.Entity("DBHandler.Models.Expediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("BOOLEAN");

                    b.Property<int>("AsesorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CampoValorJson")
                        .HasColumnType("CLOB");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int?>("EtapaDetalleId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("EtapaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NombreArchivoHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("AsesorId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Estatus");

                    b.HasIndex("EtapaDetalleId");

                    b.HasIndex("EtapaId");

                    b.HasIndex("FechaIngreso");

                    b.ToTable("EXPEDIENTES", (string)null);
                });

            modelBuilder.Entity("DBHandler.Models.ExpedienteDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("EXPEDIENTE_DETALLES", (string)null);
                });

            modelBuilder.Entity("DBHandler.Models.Flujo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Detalle")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("FLUJOS", (string)null);
                });

            modelBuilder.Entity("DBHandler.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Username");

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("DBHandler.Models.Campo", b =>
                {
                    b.HasOne("DBHandler.Models.Etapa", "Etapa")
                        .WithMany()
                        .HasForeignKey("EtapaId");

                    b.HasOne("DBHandler.Models.Flujo", "Flujo")
                        .WithMany("Campos")
                        .HasForeignKey("FlujoId");

                    b.Navigation("Etapa");

                    b.Navigation("Flujo");
                });

            modelBuilder.Entity("DBHandler.Models.Etapa", b =>
                {
                    b.HasOne("DBHandler.Models.Flujo", "Flujo")
                        .WithMany("Etapas")
                        .HasForeignKey("FlujoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flujo");
                });

            modelBuilder.Entity("DBHandler.Models.EtapaDetalle", b =>
                {
                    b.HasOne("DBHandler.Models.Etapa", "Etapa")
                        .WithMany("EtapaDetalles")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");
                });

            modelBuilder.Entity("DBHandler.Models.Expediente", b =>
                {
                    b.HasOne("DBHandler.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("AsesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBHandler.Models.EtapaDetalle", "EtapaDetalle")
                        .WithMany()
                        .HasForeignKey("EtapaDetalleId");

                    b.HasOne("DBHandler.Models.Etapa", "Etapa")
                        .WithMany()
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");

                    b.Navigation("EtapaDetalle");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DBHandler.Models.ExpedienteDetalle", b =>
                {
                    b.HasOne("DBHandler.Models.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("DBHandler.Models.Etapa", b =>
                {
                    b.Navigation("EtapaDetalles");
                });

            modelBuilder.Entity("DBHandler.Models.Flujo", b =>
                {
                    b.Navigation("Campos");

                    b.Navigation("Etapas");
                });
#pragma warning restore 612, 618
        }
    }
}
