// <auto-generated />
using System;
using DBHandler.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DBHandler.Migrations
{
    [DbContext(typeof(LoginDbContext))]
    [Migration("20250914044031_QueryCompleto")]
    partial class QueryCompleto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DBHandler.Models.UsuariosNida", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDUSUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool?>("Bloqueado")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("BLOQUEADO");

                    b.Property<bool?>("CambiarClave")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("CAMBIARCLAVE");

                    b.Property<string>("Clave")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLAVE");

                    b.Property<string>("ClaveFea")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLAVE_FEA");

                    b.Property<string>("CodigoVerificacion")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODIGO_VERIFICACION");

                    b.Property<string>("DirectorGestion")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DIRECTOR_GESTION");

                    b.Property<string>("EstadoCodigo")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ESTADO_CODIGO");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHACREACION");

                    b.Property<string>("Firma")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FIRMA");

                    b.Property<string>("FirmaElectronica")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FIRMA_ELECTRONICA");

                    b.Property<int?>("IdRol")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDROL");

                    b.Property<int?>("IdSistema")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDSISTEMA");

                    b.Property<string>("Nit")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NIT");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOMBREUSUARIO");

                    b.Property<string>("PasswordFea")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PASSWORD_FEA");

                    b.Property<string>("PinFea")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PIN_FEA");

                    b.Property<DateTime?>("UltimoCambioClave")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ULTIMO_CAMBIO_CLAVE");

                    b.Property<string>("UsernameFea")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("USERNAME_FEA");

                    b.Property<string>("UsuarioFea")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("USUARIO_FEA");

                    b.Property<string>("VersionFea")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("VERSION_FEA");

                    b.HasKey("IdUsuario");

                    b.ToTable("USUARIOSNIDA", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
