// <auto-generated />
using System;
using DBHandler.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DBHandler.Migrations
{
    [DbContext(typeof(DBHandlerContext))]
    partial class DBHandlerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TANGRAM")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DBHandler.Models.Campo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Activo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Editable")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("EtapaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("FlujoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Opciones")
                        .HasColumnType("CLOB");

                    b.Property<int>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("Requerido")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("EtapaId");

                    b.HasIndex("FlujoId");

                    b.ToTable("CAMPOS", "TANGRAM");
                });

            modelBuilder.Entity("DBHandler.Models.Etapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Activo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Detalle")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("FinDeFlujo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("FlujoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("FlujoId");

                    b.ToTable("ETAPAS", "TANGRAM");
                });

            modelBuilder.Entity("DBHandler.Models.EtapaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Activo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Detalle")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("EtapaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("EtapaId");

                    b.ToTable("ETAPA_DETALLES", "TANGRAM");
                });

            modelBuilder.Entity("DBHandler.Models.Expediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Activo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("AsesorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CampoValorJson")
                        .HasColumnType("CLOB");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int?>("EtapaDetalleId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("EtapaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ExpedienteRelacionadoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NombreArchivoHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("RemitenteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("AsesorId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Estatus");

                    b.HasIndex("EtapaDetalleId");

                    b.HasIndex("EtapaId");

                    b.HasIndex("ExpedienteRelacionadoId");

                    b.HasIndex("FechaIngreso");

                    b.HasIndex("RemitenteId");

                    b.ToTable("EXPEDIENTES", "TANGRAM");
                });

            modelBuilder.Entity("DBHandler.Models.ExpedienteDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsesorAnteriorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("AsesorNuevorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EstatusAnterior")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EstatusNuevo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("EtapaAnteriorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("EtapaDetalleAnteriorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("EtapaDetalleNuevaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("EtapaNuevaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NombreArchivoHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AsesorAnteriorId");

                    b.HasIndex("AsesorNuevorId");

                    b.HasIndex("EtapaAnteriorId");

                    b.HasIndex("EtapaDetalleAnteriorId");

                    b.HasIndex("EtapaDetalleNuevaId");

                    b.HasIndex("EtapaNuevaId");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("EXPEDIENTE_DETALLES", "TANGRAM");
                });

            modelBuilder.Entity("DBHandler.Models.ExpedienteNotas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsesorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nota")
                        .HasColumnType("CLOB");

                    b.HasKey("Id");

                    b.HasIndex("AsesorId");

                    b.HasIndex("ExpedienteId");

                    b.HasIndex("FechaIngreso");

                    b.ToTable("EXPEDIENTE_NOTAS", "TANGRAM");
                });

            modelBuilder.Entity("DBHandler.Models.Flujo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Activo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CierreArchivado")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CierreDevolucionAlRemitente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CierreEnviadoAJudicial")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Correlativo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Detalle")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("FlujoAsociado")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("FLUJOS", "TANGRAM");
                });

            modelBuilder.Entity("DBHandler.Models.Remitente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Activo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.ToTable("REMITENTE", "TANGRAM");
                });

            modelBuilder.Entity("DBHandler.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Activo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("NuevaTerminal")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<int>("Operativo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Terminal")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Username");

                    b.ToTable("USUARIOS", "TANGRAM");
                });

            modelBuilder.Entity("DBHandler.Models.Campo", b =>
                {
                    b.HasOne("DBHandler.Models.Etapa", "Etapa")
                        .WithMany()
                        .HasForeignKey("EtapaId");

                    b.HasOne("DBHandler.Models.Flujo", "Flujo")
                        .WithMany("Campos")
                        .HasForeignKey("FlujoId");

                    b.Navigation("Etapa");

                    b.Navigation("Flujo");
                });

            modelBuilder.Entity("DBHandler.Models.Etapa", b =>
                {
                    b.HasOne("DBHandler.Models.Flujo", "Flujo")
                        .WithMany("Etapas")
                        .HasForeignKey("FlujoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flujo");
                });

            modelBuilder.Entity("DBHandler.Models.EtapaDetalle", b =>
                {
                    b.HasOne("DBHandler.Models.Etapa", "Etapa")
                        .WithMany("EtapaDetalles")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");
                });

            modelBuilder.Entity("DBHandler.Models.Expediente", b =>
                {
                    b.HasOne("DBHandler.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("AsesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBHandler.Models.EtapaDetalle", "EtapaDetalle")
                        .WithMany()
                        .HasForeignKey("EtapaDetalleId");

                    b.HasOne("DBHandler.Models.Etapa", "Etapa")
                        .WithMany()
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBHandler.Models.Expediente", "ExpedienteRelacionado")
                        .WithMany()
                        .HasForeignKey("ExpedienteRelacionadoId");

                    b.HasOne("DBHandler.Models.Remitente", "Remitente")
                        .WithMany()
                        .HasForeignKey("RemitenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");

                    b.Navigation("EtapaDetalle");

                    b.Navigation("ExpedienteRelacionado");

                    b.Navigation("Remitente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DBHandler.Models.ExpedienteDetalle", b =>
                {
                    b.HasOne("DBHandler.Models.Usuario", "AsesorAnterior")
                        .WithMany()
                        .HasForeignKey("AsesorAnteriorId");

                    b.HasOne("DBHandler.Models.Usuario", "AsesorNuevo")
                        .WithMany()
                        .HasForeignKey("AsesorNuevorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBHandler.Models.Etapa", "EtapaAnterior")
                        .WithMany()
                        .HasForeignKey("EtapaAnteriorId");

                    b.HasOne("DBHandler.Models.EtapaDetalle", "EtapaDetalleAnterior")
                        .WithMany()
                        .HasForeignKey("EtapaDetalleAnteriorId");

                    b.HasOne("DBHandler.Models.EtapaDetalle", "EtapaDetalleNueva")
                        .WithMany()
                        .HasForeignKey("EtapaDetalleNuevaId");

                    b.HasOne("DBHandler.Models.Etapa", "EtapaNueva")
                        .WithMany()
                        .HasForeignKey("EtapaNuevaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBHandler.Models.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsesorAnterior");

                    b.Navigation("AsesorNuevo");

                    b.Navigation("EtapaAnterior");

                    b.Navigation("EtapaDetalleAnterior");

                    b.Navigation("EtapaDetalleNueva");

                    b.Navigation("EtapaNueva");

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("DBHandler.Models.ExpedienteNotas", b =>
                {
                    b.HasOne("DBHandler.Models.Usuario", "Asesor")
                        .WithMany()
                        .HasForeignKey("AsesorId");

                    b.Navigation("Asesor");
                });

            modelBuilder.Entity("DBHandler.Models.Etapa", b =>
                {
                    b.Navigation("EtapaDetalles");
                });

            modelBuilder.Entity("DBHandler.Models.Flujo", b =>
                {
                    b.Navigation("Campos");

                    b.Navigation("Etapas");
                });
#pragma warning restore 612, 618
        }
    }
}
